name: My-GitHubActions-Basics

on: 
  push:
    branches:
      -master
      
jobs:
  my_testing:
  
    runs-on: ubuntu-latest 
    
    steps:
      
    - name: Git clon—É my repo
      uses: actions/checkout@v1
    
