name: My-GitHubActions-Basics1

on: 
  push:
    branches:
      -master
      
jobs:
  my_testing:
    runs-on: ubuntu-latest 
    
    steps:
      
    - name: Git clone my repo
      uses: actions/setup-node@v1

