name:  Test-LearningQAAuto
on: push
jobs:
  test_my-node:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test my code
        run: npm run test

